language: perl6
sudo: false
perl6:
  - latest
  - '2019.11'
install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef build .
matrix:
    include:
    - os: linux
    - os: osx
      addons:
        apt:
          packages:
            - freetype
script:
  - prove -ve "raku -I."
  - zef install .
